### ISSUE TITLE
C++ compiler failed while compiling libyuv.cpp.

### ISSUE THREAD

**Issue by woai100deren** [908657085/rgb2yuv#1]
代码跑起来：C++ compiler failed while compiling libyuv.cpp.

**Comment by 908657085** [comment]
请添加 c++编译需要的相应头文件

首先用 locate 查找丢失文件位置
然后在 build.gradle 中添加文件引用,示例如下
 cppFlags.add('-I' + '/usr/lib/jvm/include')
 cppFlags.add('-I' + '/usr/lib/jvm/include/linux')
 cppFlags.add('-I' + '/usr/include')
